### ISSUE TITLE
App not opening/working on Ubuntu 16.04

### ISSUE THREAD

**Issue by kofimokome** [JamezQ/Palaver#109]
Please I recently followed the steps from your Youtube video on how to install the voice recognition software. But Whenever I press Ctrl+L, nothing happens. I am using Ubuntu 16.04 64bit

**Comment by dangreenisrael** [comment]
@kofimokome I don't think that this project is supported anymore

**Comment by JamezQ** [comment]
@everyone Google has closed up the API the Palaver was using. So the voice recognition part would have to be replaced in order for the system to work.

**Comment by dangreenisrael** [comment]
@JamezQ Perhaps you could put something in the README explaining that this is not a working project

**Comment by JamezQ** [comment]
Multiple places

**Comment by JamezQ** [comment]
Okay.

**Comment by dangreenisrael** [comment]
Thanks @JamezQ

**Comment by kofimokome** [comment]
Thanks @JamezQ . I pray this project continues maybe with another API

**Comment by FreeScholar** [comment]
Any updates, this looks sad.

**Comment by BrettMayson** [comment]
> Any updates, this looks sad.

From the readme

> NOTE: GOOGLE has since closed their speech recognition api. Because of this, another API would have to be used to allow palaver to work.
