### ISSUE TITLE
Suggestion: Use OpenAI Whisper 

### ISSUE THREAD

**Issue by 749** [JamezQ/Palaver#112]
OpenAI Whisper is a terminal application which can do Speech to text recognition. Please consider replacing the Google API with it.

See https://github.com/openai/whisper for more information about the application.

**Comment by BrettMayson** [comment]
This is very much a dead project, and has been for about 11 years

**Comment by JamezQ** [comment]
Hi all, that is correct. Honestly it warms my heart to see the enthusiasm for the project so many years later, I’ll give a bit of history:

When I first made this project I was still a kid, I was in high school and I hated doing school work, so I would program instead, something I actually enjoyed. The fundamentals of Palaver were something I made binge programming over a weekend.

I thought what I made was cool, so I made a quick video and posted it https://youtu.be/HfrQrjH3AGw?si=qBux9m8rUkaaAoFL. And overnight I had a ton of comments, emails being sent to me, etc. Which really I had no idea how to deal with. The open source community helped me out a lot here. Ultimately though, I mismanaged the project and learned a lot in the process.

So now I’m 30, I have two kids and a job in FAANG, I still love programming but I haven’t had free time to do so in a long time. 

My point to anyone that made it this far is, if you have the right solution at the right time, go for it, it may just take a night or too of programming to make something people love, and if you were to remake Palaver you should, I bet something much better could be made. 

Be careful of pull requests, too many cooks spoil the soup, have a vision and define a proper build process, don’t let anything that breaks the build merge. 

Good Luck everyone, if you ever find yourself in the Bay Area let’s grab a coffee :)
